{
  "hash": "e80e336b404064e2fee1a5b234d42298",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Econometría de Series de Tiempo\"\nsubtitle: \"Volatilidad de Tasas de Interés en República Dominicana <br> José Antonio Burgos (25-0140)\"\nformat:\n   html: \n     lang: es\n     embed-resources: true\n     warning: false\n     message: false\n     fig-cap-location: top\n     theme: united\n     css: styles.css\n---\n\n\n\n::: {.cell}\n\n:::\n\n\n\\newline\n\n## Preparación de datos y tranformaciones\n\nSe procedió a la carga de las tasas de interés pasivas con frecuencia semanal, las cuales fueron posteriormente transformadas a objetos de series de tiempo utilizando la clase xts. El conjunto de datos incluye las tasas correspondientes a depósitos a 30 días, depósitos a más de 360 días, así como la tasa promedio ponderada del sistema. Estas series son publicadas por el Banco Central de la República Dominicana.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntasas_pasivas <- readxl::read_excel(\"tasas_pasivas_semanal.xlsx\") \n\ndata <- tasas_pasivas |> \n    mutate(fecha = as.Date(week_inicio)) |> \n    arrange(fecha)\n\nts_data <- xts(tasas_pasivas[,-c(1,2)], order.by = data$fecha)\n```\n:::\n\n\n\n## Exploración de las Series\n\n### En niveles\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(ts_data) +\n    labs(x = \"Periodo\", y = \"Tasas\") + \n    ggplot2::scale_y_continuous(labels = \\(x) scales::comma(x, suffix = \".0 %\"))\n```\n\n::: {.cell-output-display}\n![Evolución de las Tasas Pasivas en Niveles](practica_guiada_files/figure-html/fig-tasa-1.png){#fig-tasa width=672}\n:::\n:::\n\n\nComo se observa @fig-tasa exites un nivel de volatilidad en las tres tasas presentadas, pero como es de esperar, se registra un nivel más alto de volatilidad a medida que nos movemos de una tasa de mayor plazo a menor subsesivamente.\n\nExisten episodiso de alta volatilidad, principalmente en coyunturas asociadas a eventos de crisis internacionales. \n\n\n### En diferencias logarítmicas\n\n\n::: {.cell}\n\n```{.r .cell-code}\nts_ld <- diff(log(ts_data))*100\n\nautoplot(ts_ld) + labs(x = \"Periodo\", y = \"Tasas\")\n```\n\n::: {.cell-output-display}\n![Evolución de las Tasas Pasivas en diferencias logarítmicas](practica_guiada_files/figure-html/fig-tasa-log-diff-1.png){#fig-tasa-log-diff width=672}\n:::\n:::\n\n\n\nLas series en diferencias logarítmicas presentan un comportamiento consistente con estacionariedad en media, dado que oscilan alrededor de un valor cercano a cero y no evidencian tendencias persistentes a lo largo del tiempo. Este resultado es coherente con la transformación aplicada, la cual suele eliminar la no estacionariedad presente en los niveles de las series.\n\nNo obstante, aunque la media parece estable, la varianza no es constante. Se identifican claramente períodos de baja variabilidad seguidos de episodios de alta volatilidad, especialmente en años recientes, donde las fluctuaciones son más pronunciadas. Este patrón refleja la presencia de clusters de volatilidad, es decir, agrupamientos de alta y baja variabilidad en el tiempo.\n\n### En diferencias logarítmicas al cuadrado\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(ts_ld^2) + labs(x = \"Periodo\", y = \"Tasas\")\n```\n\n::: {.cell-output-display}\n![En diferencias logarítmicas al cuadrado](practica_guiada_files/figure-html/fig-tasa-lg-dff2-1.png){#fig-tasa-lg-dff2 width=672}\n:::\n:::\n\n\nEn las tres series de la @fig-tasa-lg-dff2, los picos de volatilidad no aparecen de forma aislada y aleatoria, sino que se agrupan en el tiempo; cuando hay un valor elevado del cuadrado de la diferencia logarítmica, es muy probable que los períodos adyacentes también presenten valores elevados. Esto es precisamente la firma estadística de autocorrelación en la varianza (también llamada autocorrelación en los cuadrados de los residuos). Hay períodos largos de baja volatilidad interrumpidos por episodios de alta volatilidad \npersistente, eso es `clustering`, e implica autocorrelación significativa en la varianza.\n\n\n\n## División por Régimen\n\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {layout-ncol=2}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(r_pre) + labs(x = \"Periodo\", y = \"Tasas\")\n```\n\n::: {.cell-output-display}\n![En diferencias logarítmicas pre EMI](practica_guiada_files/figure-html/fig-tasa-preemi-1.png){#fig-tasa-preemi width=672}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(r_post) + labs(x = \"Periodo\", y = \"Tasas\")\n```\n\n::: {.cell-output-display}\n![En diferencias logarítmicas post EMI](practica_guiada_files/figure-html/fig-tasa-postemi-1.png){#fig-tasa-postemi width=672}\n:::\n:::\n\n\n:::\n\n\nLas @fig-tasa-preemi y @fig-tasa-postemi presentan las diferencias logarítmicas de las tasas pasivas en los subperíodos pre y post adopción del Esquema de Metas de Inflación (EMI). En el período pre-EMI (2008–2012), las tres series muestran fluctuaciones de amplitud moderada y sin episodios de volatilidad extrema sostenida. Por el contrario, en el período post-EMI (2013–2025) se observa un marcado clustering de volatilidad, especialmente durante 2019–2022, donde tp_30d y tp_m360 registran excursiones que superan los ±75 puntos, reflejando el impacto de los choques macroeconómicos asociados a la pandemia del COVID-19.\n\n\n## Modelo de la Media\n\n\nVamos a seleccionar la tasa pasiva de corto plazo, las de un periodo de de 30 días, ya que esta es la que muestra la mayor variabilidad en los dos subperiodos de la adopción del EMI. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(fit_mean <- auto.arima(r_pre[,1])) |> modelsummary()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_k6c9j3g68jziwpkm54i4 = TinyTable.createTableFunctions(\"tinytable_k6c9j3g68jziwpkm54i4\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '11', j: 2 } ], css_id: 'tinytable_css_yixdhzb4iiyl9qz6o5dm',}, \n          { positions: [ { i: '6', j: 2 } ], css_id: 'tinytable_css_pioyhara82jj0zz5bdhh',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 } ], css_id: 'tinytable_css_2p68kkdh2gv0jcx1b3nn',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_fjre2st2g3qq5liflgk1',}, \n          { positions: [ { i: '11', j: 1 } ], css_id: 'tinytable_css_kk3068bbhkxo9q48l7eo',}, \n          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_5gcd75e4a7q613r8xu4x',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 } ], css_id: 'tinytable_css_rxm09wcjxh3uj72h8k6j',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_79duxantgfiajwosbvua',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_k6c9j3g68jziwpkm54i4.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_k6c9j3g68jziwpkm54i4 td.tinytable_css_yixdhzb4iiyl9qz6o5dm, #tinytable_k6c9j3g68jziwpkm54i4 th.tinytable_css_yixdhzb4iiyl9qz6o5dm {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_k6c9j3g68jziwpkm54i4 td.tinytable_css_pioyhara82jj0zz5bdhh, #tinytable_k6c9j3g68jziwpkm54i4 th.tinytable_css_pioyhara82jj0zz5bdhh {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_k6c9j3g68jziwpkm54i4 td.tinytable_css_2p68kkdh2gv0jcx1b3nn, #tinytable_k6c9j3g68jziwpkm54i4 th.tinytable_css_2p68kkdh2gv0jcx1b3nn { text-align: center }\n    #tinytable_k6c9j3g68jziwpkm54i4 td.tinytable_css_fjre2st2g3qq5liflgk1, #tinytable_k6c9j3g68jziwpkm54i4 th.tinytable_css_fjre2st2g3qq5liflgk1 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_k6c9j3g68jziwpkm54i4 td.tinytable_css_kk3068bbhkxo9q48l7eo, #tinytable_k6c9j3g68jziwpkm54i4 th.tinytable_css_kk3068bbhkxo9q48l7eo {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_k6c9j3g68jziwpkm54i4 td.tinytable_css_5gcd75e4a7q613r8xu4x, #tinytable_k6c9j3g68jziwpkm54i4 th.tinytable_css_5gcd75e4a7q613r8xu4x {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_k6c9j3g68jziwpkm54i4 td.tinytable_css_rxm09wcjxh3uj72h8k6j, #tinytable_k6c9j3g68jziwpkm54i4 th.tinytable_css_rxm09wcjxh3uj72h8k6j { text-align: left }\n    #tinytable_k6c9j3g68jziwpkm54i4 td.tinytable_css_79duxantgfiajwosbvua, #tinytable_k6c9j3g68jziwpkm54i4 th.tinytable_css_79duxantgfiajwosbvua {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_k6c9j3g68jziwpkm54i4\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">(1)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">ar1</td>\n                  <td data-row=\"1\" data-col=\"2\">-0.839</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.102)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">ma1</td>\n                  <td data-row=\"3\" data-col=\"2\">0.260</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.128)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">ma2</td>\n                  <td data-row=\"5\" data-col=\"2\">-0.311</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.098)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"7\" data-col=\"2\">208</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">AIC</td>\n                  <td data-row=\"8\" data-col=\"2\">1653.1</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">BIC</td>\n                  <td data-row=\"9\" data-col=\"2\">1666.5</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">RMSE</td>\n                  <td data-row=\"10\" data-col=\"2\">12.61</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">x</td>\n                  <td data-row=\"11\" data-col=\"2\">0.29871520651479</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nEl modelo seleccionado es un ARMA(1,2), lo que indica que la serie presenta dependencia tanto en sus valores pasados como en choques anteriores. No obstante, para validar completamente la idoneidad del modelo, es imprescindible analizar los residuos; en particular, verificar que no presenten autocorrelación, condición necesaria para considerarlos como ruido blanco.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(resid_pre <- residuals(fit_mean)) |> plot(xlab = \"Periodo\", ylab = \"Residuos\", col = \"darkblue\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![Residuos del modelo estimado](practica_guiada_files/figure-html/fig-residual-ruido-blanco-1.png){#fig-residual-ruido-blanco width=672}\n:::\n:::\n\n\n\nLos residuos presentados en @fig-residual-ruido-blanco cumplen parcialmente con las condiciones de ruido blanco (media cero y sin autocorrelación evidente en media), pero muestran indicios de heterocedasticidad condicional. Por tanto, sería apropiado avanzar hacia la estimación de un modelo GARCH, que permita modelar explícitamente la dinámica de la volatilidad observada.\n\n\n## Test ARCH\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nArchTest(resid_pre, lags =12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tARCH LM-test; Null hypothesis: no ARCH effects\n\ndata:  resid_pre\nChi-squared = 13.518, df = 12, p-value = 0.3326\n```\n\n\n:::\n:::\n\n\n\nEl contraste tiene como hipótesis nula la ausencia de efectos ARCH (es decir, varianza condicional constante). En este caso, el valor p obtenido (p-value = 0.3326) es considerablemente mayor que niveles de significancia habituales (1%, 5% o incluso 10%). Por tanto, no se rechaza la hipótesis nula.\n\nEn consecuencia, no hay evidencia estadísticamente significativa de heterocedasticidad condicional en los residuos del modelo ARMA(1,2). Esto sugiere que la varianza de los errores puede considerarse aproximadamente constante en el tiempo, y que la especificación en media parece adecuada sin necesidad de modelar la volatilidad mediante un modelo GARCH.\n\n\n## Modelo GARCH(1,1)\n\nEstimar el siguiente modelo GARCH(1,1):\n\n$$\\sigma^2_t = \\alpha_0 + \\alpha_1\\epsilon^2_{t-1} + \\beta_1\\sigma^2_{t-1}$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspec <- ugarchspec(variance.model = list(model =\"sGARCH\"), mean.model = list(armaOrder =c(1 ,1)))\n\nfit <- ugarchfit(spec , data = r_pre[,1])\n```\n:::\n\n\n\n\nCalcular: \n\n$$\\alpha + \\beta = 0.14910+0.79396=0.94306$$\n\nSí, existe alta persistencia en la volatilidad, ver @sec-apendicea.\n\nEl valor de $\\alpha + \\beta =0.94306$ es muy cercano a 1, lo que indica que los choques a la volatilidad tienden a disiparse lentamente en el tiempo. En modelos GARCH(1,1), cuando esta suma es elevada (especialmente mayor a 0.9), se interpreta como evidencia de que la volatilidad es altamente persistente.\n\n\n## Modelos Extendidos\n\n### EGARCH\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspec_egarch <- ugarchspec(variance.model = list(model = \"eGARCH\"), mean.model = list(armaOrder = c(0,0)))\n\n(fit_egarch <- fit_egarch <- ugarchfit(spec_egarch, r_pre[,1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n*---------------------------------*\n*          GARCH Model Fit        *\n*---------------------------------*\n\nConditional Variance Dynamics \t\n-----------------------------------\nGARCH Model\t: eGARCH(1,1)\nMean Model\t: ARFIMA(0,0,0)\nDistribution\t: norm \n\nConvergence Problem:\nSolver Message: \n```\n\n\n:::\n:::\n\n\n### GJR GARCH\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspec_gjr <- ugarchspec(\n  variance.model = list(model = \"gjrGARCH\"),\n  mean.model = list(armaOrder = c(0,0))\n)\n\nfit_gjr <- ugarchfit(spec_gjr, r_pre[,1])\n```\n:::\n\n\n\n### IGARCH\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspec_igarch <- ugarchspec(\n  variance.model = list(model = \"iGARCH\"),\n  mean.model = list(armaOrder = c(0,0))\n)\n\nfit_igarch <- ugarchfit(spec_igarch, r_pre[,1])\n```\n:::\n\n\n#### Asimetría en la volatilidad\n\nNo se encuentra evidencia de asimetría en la volatilidad. En el modelo GJR-GARCH (ver @sec-apendiceb), el parámetro asociado al efecto asimétrico ($\\lambda_1$) no resulta estadísticamente significativo (p-value elevado), lo que indica que no existen diferencias relevantes en la respuesta de la volatilidad ante choques positivos y negativos.\n\nAdicionalmente, los resultados del Sign Bias Test refuerzan esta conclusión, ya que no se detectan efectos significativos asociados al signo de los shocks.\n\n\n#### Impacto de shocks negativos\n\nEn línea con lo anterior, no hay evidencia de que los shocks negativos tengan un mayor impacto sobre la volatilidad en comparación con los positivos. La falta de significancia del término asimétrico implica que el modelo no captura efectos tipo *leverage*, es decir, no se observa que las caídas en las tasas generen incrementos desproporcionados en la volatilidad.\n\n#### Persistencia de la volatilidad\n\nSí se observa una alta persistencia en la volatilidad, ir al @sec-apendicec. En el modelo GJR-GARCH, la suma de los parámetros $\\alpha_1 + \\beta_1$ es elevada (aproximadamente 0.90), lo que sugiere que los efectos de los shocks sobre la volatilidad se disipan lentamente.\n\nPor su parte, el modelo iGARCH impone explícitamente una estructura de persistencia extrema, donde los choques tienen efectos permanentes sobre la varianza condicional. Sin embargo, este resultado debe interpretarse con cautela, ya que puede reflejar una sobreparametrización más que una verdadera dinámica de largo plazo.\n\n\n## Comparación Pre vs Post 2012\n\n\n### Estimación pre y post EMI\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_pre  <- ugarchfit(spec, data = r_pre[,1])\nfit_post <- ugarchfit(spec, data = r_post[,1])\n```\n:::\n\n\n###  Persistencia\n\n$$(\\alpha+\\beta)$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extraer coeficientes\ncoef_pre  <- coef(fit_pre)\ncoef_post <- coef(fit_post)\n\n(persist_pre  <- coef_pre[\"alpha1\"] + coef_pre[\"beta1\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   alpha1 \n0.9430608 \n```\n\n\n:::\n\n```{.r .cell-code}\n(persist_post <- coef_post[\"alpha1\"] + coef_post[\"beta1\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   alpha1 \n0.9936932 \n```\n\n\n:::\n:::\n\n\n\n\n### Nivel de volatilidad\n\n\n####  Mean: \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvol_pre  <- sigma(fit_pre)^2\nvol_post <- sigma(fit_post)^2\n\nmean(vol_pre)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 174.419\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(vol_post)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 274.5078\n```\n\n\n:::\n:::\n\n\n\n#### Gráficos\n\n::: {layout-ncol=2}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(sigma(fit_pre))\n```\n\n::: {.cell-output-display}\n![Volatilidad Condicional Pre 2012](practica_guiada_files/figure-html/fig-volatilidad-pre-2012-1.png){#fig-volatilidad-pre-2012 width=672}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(sigma(fit_post))\n```\n\n::: {.cell-output-display}\n![Volatilidad Condicional Post 2012](practica_guiada_files/figure-html/fig-volatilidad-post-2012-1.png){#fig-volatilidad-post-2012 width=672}\n:::\n:::\n\n\n:::\n\n\n#### Consideraciones y comentarios\n\nCon base en los resultados estimados, la volatilidad sí aumentó tras la adopción del esquema de metas de inflación. La varianza condicional promedio pasó de 174.42 en el período pre a 274.51 en el período post, lo que indica un entorno monetario más volátil después del cambio de régimen.\n\nEn términos de persistencia, también se observa un incremento claro: $(\\alpha+\\beta)$ pasó de 0.9431 en el período pre a 0.9937 en el período post. Esto sugiere que, luego de la adopción de metas de inflación, los choques sobre la volatilidad tardaron más en disiparse y dejaron una huella más prolongada en el tiempo. En consecuencia, sí se evidencia una persistencia del riesgo muy alta, especialmente en el período posterior.\n\nDesde la perspectiva de política monetaria, estos resultados implican que el mercado monetario se volvió más sensible a perturbaciones y que la autoridad monetaria pudo haber enfrentado un entorno en el que los shocks sobre las tasas de interés tuvieron efectos más duraderos. Esto exige una respuesta de política más cuidadosa, con mayor énfasis en la comunicación, la credibilidad del régimen y el monitoreo permanente de las condiciones financieras, ya que pequeñas perturbaciones pueden traducirse en episodios de volatilidad prolongada.\n\nEn síntesis, tras la adopción de metas de inflación, la volatilidad aumentó, el riesgo se volvió más persistente y el mercado monetario mostró una dinámica más sensible a los shocks, lo que refuerza la importancia de una política monetaria bien anclada y preventiva.\n\n\n\n\n\n\n\n\n## Apéndices\n\n### Apéndice A: Estimación del modelo GARCH(1,1) {#sec-apendicea}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n*---------------------------------*\n*          GARCH Model Fit        *\n*---------------------------------*\n\nConditional Variance Dynamics \t\n-----------------------------------\nGARCH Model\t: sGARCH(1,1)\nMean Model\t: ARFIMA(1,0,1)\nDistribution\t: norm \n\nOptimal Parameters\n------------------------------------\n        Estimate  Std. Error  t value Pr(>|t|)\nmu      -0.27821    0.473241 -0.58788 0.556611\nar1     -0.34519    0.197057 -1.75172 0.079822\nma1     -0.22134    0.217240 -1.01887 0.308265\nomega   11.33151    7.231495  1.56697 0.117122\nalpha1   0.14910    0.072464  2.05759 0.039630\nbeta1    0.79396    0.080398  9.87534 0.000000\n\nRobust Standard Errors:\n        Estimate  Std. Error  t value Pr(>|t|)\nmu      -0.27821    0.521466 -0.53351 0.593677\nar1     -0.34519    0.312904 -1.10318 0.269950\nma1     -0.22134    0.376084 -0.58854 0.556172\nomega   11.33151    6.788181  1.66930 0.095058\nalpha1   0.14910    0.081813  1.82246 0.068385\nbeta1    0.79396    0.091567  8.67080 0.000000\n\nLogLikelihood : -819.0942 \n\nInformation Criteria\n------------------------------------\n                   \nAkaike       7.9336\nBayes        8.0299\nShibata      7.9320\nHannan-Quinn 7.9725\n\nWeighted Ljung-Box Test on Standardized Residuals\n------------------------------------\n                        statistic   p-value\nLag[1]                    0.02729 8.688e-01\nLag[2*(p+q)+(p+q)-1][5]   6.04868 6.389e-05\nLag[4*(p+q)+(p+q)-1][9]  10.16317 7.848e-03\nd.o.f=2\nH0 : No serial correlation\n\nWeighted Ljung-Box Test on Standardized Squared Residuals\n------------------------------------\n                        statistic p-value\nLag[1]                     0.1052  0.7456\nLag[2*(p+q)+(p+q)-1][5]    1.6856  0.6943\nLag[4*(p+q)+(p+q)-1][9]    2.4124  0.8505\nd.o.f=2\n\nWeighted ARCH LM Tests\n------------------------------------\n            Statistic Shape Scale P-Value\nARCH Lag[3]     1.466 0.500 2.000  0.2260\nARCH Lag[5]     1.804 1.440 1.667  0.5162\nARCH Lag[7]     2.004 2.315 1.543  0.7165\n\nNyblom stability test\n------------------------------------\nJoint Statistic:  1.3556\nIndividual Statistics:             \nmu     0.1674\nar1    0.1305\nma1    0.2824\nomega  0.3115\nalpha1 0.1610\nbeta1  0.3069\n\nAsymptotic Critical Values (10% 5% 1%)\nJoint Statistic:     \t 1.49 1.68 2.12\nIndividual Statistic:\t 0.35 0.47 0.75\n\nSign Bias Test\n------------------------------------\n                   t-value   prob sig\nSign Bias           1.2726 0.2046    \nNegative Sign Bias  0.7897 0.4306    \nPositive Sign Bias  0.2452 0.8066    \nJoint Effect        2.0579 0.5605    \n\n\nAdjusted Pearson Goodness-of-Fit Test:\n------------------------------------\n  group statistic p-value(g-1)\n1    20     14.31       0.7655\n2    30     29.12       0.4591\n3    40     27.77       0.9102\n4    50     44.88       0.6406\n\n\nElapsed time : 0.121057 \n```\n\n\n:::\n:::\n\n\n\n### Apéndice B: Estimación del modelo GJR GARCH {#sec-apendiceb}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_gjr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n*---------------------------------*\n*          GARCH Model Fit        *\n*---------------------------------*\n\nConditional Variance Dynamics \t\n-----------------------------------\nGARCH Model\t: gjrGARCH(1,1)\nMean Model\t: ARFIMA(0,0,0)\nDistribution\t: norm \n\nOptimal Parameters\n------------------------------------\n        Estimate  Std. Error  t value Pr(>|t|)\nmu     -0.691101    0.930176 -0.74298 0.457495\nomega  15.603654   10.723444  1.45510 0.145642\nalpha1  0.150737    0.089879  1.67712 0.093519\nbeta1   0.752120    0.097329  7.72757 0.000000\ngamma1  0.094272    0.164753  0.57220 0.567184\n\nRobust Standard Errors:\n        Estimate  Std. Error  t value Pr(>|t|)\nmu     -0.691101    0.610998  -1.1311 0.258012\nomega  15.603654    9.137554   1.7076 0.087703\nalpha1  0.150737    0.098313   1.5332 0.125216\nbeta1   0.752120    0.094134   7.9899 0.000000\ngamma1  0.094272    0.177237   0.5319 0.594796\n\nLogLikelihood : -844.9818 \n\nInformation Criteria\n------------------------------------\n                   \nAkaike       8.1729\nBayes        8.2531\nShibata      8.1718\nHannan-Quinn 8.2053\n\nWeighted Ljung-Box Test on Standardized Residuals\n------------------------------------\n                        statistic   p-value\nLag[1]                      40.11 2.396e-10\nLag[2*(p+q)+(p+q)-1][2]     43.36 3.394e-12\nLag[4*(p+q)+(p+q)-1][5]     56.18 9.992e-16\nd.o.f=0\nH0 : No serial correlation\n\nWeighted Ljung-Box Test on Standardized Squared Residuals\n------------------------------------\n                        statistic p-value\nLag[1]                    0.04293  0.8359\nLag[2*(p+q)+(p+q)-1][5]   0.38185  0.9743\nLag[4*(p+q)+(p+q)-1][9]   0.57578  0.9976\nd.o.f=2\n\nWeighted ARCH LM Tests\n------------------------------------\n            Statistic Shape Scale P-Value\nARCH Lag[3]    0.2235 0.500 2.000  0.6364\nARCH Lag[5]    0.2707 1.440 1.667  0.9480\nARCH Lag[7]    0.3418 2.315 1.543  0.9904\n\nNyblom stability test\n------------------------------------\nJoint Statistic:  0.7101\nIndividual Statistics:              \nmu     0.08102\nomega  0.31340\nalpha1 0.16376\nbeta1  0.27201\ngamma1 0.11817\n\nAsymptotic Critical Values (10% 5% 1%)\nJoint Statistic:     \t 1.28 1.47 1.88\nIndividual Statistic:\t 0.35 0.47 0.75\n\nSign Bias Test\n------------------------------------\n                   t-value   prob sig\nSign Bias          0.53181 0.5954    \nNegative Sign Bias 0.27408 0.7843    \nPositive Sign Bias 0.01391 0.9889    \nJoint Effect       1.21125 0.7503    \n\n\nAdjusted Pearson Goodness-of-Fit Test:\n------------------------------------\n  group statistic p-value(g-1)\n1    20     14.31       0.7655\n2    30     36.04       0.1724\n3    40     32.38       0.7641\n4    50     43.44       0.6971\n\n\nElapsed time : 0.1460512 \n```\n\n\n:::\n:::\n\n\n### Apéndice C: Estimación del modelo IGARCH {#sec-apendicec}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_igarch\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n*---------------------------------*\n*          GARCH Model Fit        *\n*---------------------------------*\n\nConditional Variance Dynamics \t\n-----------------------------------\nGARCH Model\t: iGARCH(1,1)\nMean Model\t: ARFIMA(0,0,0)\nDistribution\t: norm \n\nOptimal Parameters\n------------------------------------\n        Estimate  Std. Error  t value Pr(>|t|)\nmu      -0.42994    0.810816 -0.53025 0.595937\nomega    8.82055    6.312439  1.39733 0.162315\nalpha1   0.22251    0.091091  2.44269 0.014578\nbeta1    0.77749          NA       NA       NA\n\nRobust Standard Errors:\n        Estimate  Std. Error  t value Pr(>|t|)\nmu      -0.42994    0.795010 -0.54079 0.588650\nomega    8.82055    6.429122  1.37197 0.170073\nalpha1   0.22251    0.097819  2.27468 0.022925\nbeta1    0.77749          NA       NA       NA\n\nLogLikelihood : -845.749 \n\nInformation Criteria\n------------------------------------\n                   \nAkaike       8.1610\nBayes        8.2092\nShibata      8.1606\nHannan-Quinn 8.1805\n\nWeighted Ljung-Box Test on Standardized Residuals\n------------------------------------\n                        statistic   p-value\nLag[1]                      37.47 9.279e-10\nLag[2*(p+q)+(p+q)-1][2]     40.55 1.839e-11\nLag[4*(p+q)+(p+q)-1][5]     51.66 2.109e-14\nd.o.f=0\nH0 : No serial correlation\n\nWeighted Ljung-Box Test on Standardized Squared Residuals\n------------------------------------\n                        statistic p-value\nLag[1]                  0.0008577  0.9766\nLag[2*(p+q)+(p+q)-1][5] 0.4988101  0.9579\nLag[4*(p+q)+(p+q)-1][9] 0.9646227  0.9877\nd.o.f=2\n\nWeighted ARCH LM Tests\n------------------------------------\n            Statistic Shape Scale P-Value\nARCH Lag[3]    0.5322 0.500 2.000  0.4657\nARCH Lag[5]    0.7160 1.440 1.667  0.8186\nARCH Lag[7]    0.9917 2.315 1.543  0.9149\n\nNyblom stability test\n------------------------------------\nJoint Statistic:  0.4238\nIndividual Statistics:              \nmu     0.09189\nomega  0.14010\nalpha1 0.23239\n\nAsymptotic Critical Values (10% 5% 1%)\nJoint Statistic:     \t 0.846 1.01 1.35\nIndividual Statistic:\t 0.35 0.47 0.75\n\nSign Bias Test\n------------------------------------\n                   t-value   prob sig\nSign Bias           0.5626 0.5743    \nNegative Sign Bias  0.1344 0.8932    \nPositive Sign Bias  0.2645 0.7917    \nJoint Effect        1.5966 0.6602    \n\n\nAdjusted Pearson Goodness-of-Fit Test:\n------------------------------------\n  group statistic p-value(g-1)\n1    20     11.04       0.9225\n2    30     36.62       0.1563\n3    40     28.15       0.9010\n4    50     45.85       0.6018\n\n\nElapsed time : 0.01893806 \n```\n\n\n:::\n:::\n\n\n\n",
    "supporting": [
      "practica_guiada_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}